name: Test and Build

on:
  workflow_dispatch:


jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps: 
      - name: Verification des fichiers du runner
        run: ls -a -l

      - name: Clone du projet dans le runner 
        uses: actions/checkout@v6

      - name: Verification des fichiers apres l'action "checkout"
        run: ls -a -l
      
      - name: installation env node.js
        uses: actions/setup-node@v6 
      
      - name: installation env node.js
        run: npm ci
      
      - name: Lancement des tests unitaires
        run: npm run test 

      - name: Send Email
        if: failure()
        uses: ksatriow/action-mailer@v1.0.0
        with:
          smtp-server: ${{vars.SMTP_SERVER}}
          smtp-port: ${{vars.SMTP_PORT}}
          from-email: ${{ secrets.FROM_EMAIL }}
          to-email: digitalcity@yopmail.com
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "🚀 Deployment Fail!"
          body: "<h1>Your deployment failed successfully!<h1>"

      - name: Build du code TS vers le JS
        run: npm run build

      - name: Verifier le resultat de la build (Projet "Hello World")
        run: npm run start

      

       